rm(list = ls())
I.county <- read.delim("data/Cum_Infected_county_2020-12-22_updated.tsv", header = TRUE)
D.county <- read.delim("data/Cum_Death_county_2020-12-22_updated.tsv", header = TRUE)
I.state <- read.delim("data/Cum_Infected_state_2020-12-22_updated.tsv", header = TRUE)
D.state <- read.delim("data/Cum_Death_state_2020-12-22_updated.tsv", header = TRUE)
I.us <- read.delim("data/Cum_Infected_us_2020-12-22_updated.tsv", header = TRUE)
D.us <- read.delim("data/Cum_Death_us_2020-12-22_updated.tsv", header = TRUE)
save(I.county, file = "data/I.county.rda")
save(D.county, file = "data/D.county.rda")
save(I.state, file = "data/I.state.rda")
save(D.state, file = "data/D.state.rda")
save(I.us, file = "data/I.us.rda")
save(D.us, file = "data/D.us.rda")
library(cdcar)
data(I.county); dim(I.county)
data(D.county); dim(D.county)
data(I.state); dim(I.state)
data(D.state); dim(D.state)
data(I.us); dim(I.us)
data(D.us); dim(D.us)
